### ISSUE TITLE
Unexpected exception in schema registry group processing thread org.apache.kafka.common.errors.WakeupException: null

### ISSUE THREAD

**Issue by SarpongAbasimi** [embeddedkafka/embedded-kafka#288]
Hey I am seeing this error using `embedded-kaka`

```

[warn] o.a.k.c.n.Selector - [SocketServer brokerId=0] Unexpected error from /127.0.0.1; closing connection
org.apache.kafka.common.network.InvalidReceiveException: Invalid receive (size = 369296129 larger than 104857600)
	at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:105)
	at org.apache.kafka.common.network.KafkaChannel.receive(KafkaChannel.java:447)
	at org.apache.kafka.common.network.KafkaChannel.read(KafkaChannel.java:397)
  | => rat org.apache.kafka.common.network.Selector.attemptRead(Selector.java:678)
	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:580)
	at org.apache.kafka.common.network.Selector.poll(Selector.java:485)
	at kafka.network.Processor.poll(SocketServer.scala:913)
	at kafka.network.Processor.run(SocketServer.scala:816)
	at java.lang.Thread.run(Thread.java:748)
[warn] o.a.k.c.NetworkClient - [Producer clientId=producer-1] Connection to node -1 (localhost/127.0.0.1:6001) terminated during authentication. This may happen due to any of the following reasons: (1) Authentication failed due to invalid credentials with brokers older than 1.0.0, (2) Firewall blocking Kafka TLS traffic (eg it may only allow HTTPS traffic), (3) Transient network issue.
[warn] o.a.k.c.NetworkClient - [Producer clientId=producer-1] Bootstrap broker localhost:6001 (id: -1 rack: null) disconnected
[error] i.c.k.s.l.k.KafkaGroupLeaderElector - Unexpected exception in schema registry group processing thread
org.apache.kafka.common.errors.WakeupException: null
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.maybeTriggerWakeup(ConsumerNetworkClient.java:514)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:278)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:236)
  | => rat org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:227)
	at io.confluent.kafka.schemaregistry.leaderelector.kafka.SchemaRegistryCoordinator.poll(SchemaRegistryCoordinator.java:125)
	at io.confluent.kafka.schemaregistry.leaderelector.kafka.KafkaGroupLeaderElector$1.run(KafkaGroupLeaderElector.java:200)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
```

Any reason why this is the case?

**Comment by francescopellegrini** [comment]
Hi @SarpongAbasimi,
it looks like you've hit `socket.request.max.bytes`: https://kafka.apache.org/documentation/#brokerconfigs_socket.request.max.bytes

I've never experienced this error before.. may I ask you what kind of data are you sending/reading?

**Comment by SarpongAbasimi** [comment]
Hey @francescopellegrini I am sending data  which has been serialised using `avro4s`.
I actually thought that this was an embedded Kafka issue 
Ref - https://github.com/embeddedkafka/embedded-kafka-schema-registry/issues/238

**Comment by SarpongAbasimi** [comment]
Also how to you figure out that the issue was related to `socket.request.max.bytes` please?

**Comment by francescopellegrini** [comment]
> Hey @francescopellegrini I am sending data which has been serialised using `avro4s`.
> I actually thought that this was an embedded Kafka issue
> Ref - [embeddedkafka/embedded-kafka-schema-registry#238](https://github.com/embeddedkafka/embedded-kafka-schema-registry/issues/238)

Sorry, but the issue you linked has nothing to do with the aforementioned error.

> Also how to you figure out that the issue was related to `socket.request.max.bytes` please?

The second line of the stacktrace references both `InvalidReceiveException` and the default value of `socket.request.max.bytes` (104857600 bytes). Have you tried using a larger value for that setting?

**Comment by SarpongAbasimi** [comment]
@francescopellegrini nope I have not tried using a lager value for `socket.request.max.bytes` because I initially didn't understand the error myself. But I will try doing that.

**Comment by SarpongAbasimi** [comment]
> > Hey @francescopellegrini I am sending data which has been serialised using `avro4s`.
> > I actually thought that this was an embedded Kafka issue
> > Ref - [embeddedkafka/embedded-kafka-schema-registry#238](https://github.com/embeddedkafka/embedded-kafka-schema-registry/issues/238)
> 
> Sorry, but the issue you linked has nothing to do with the aforementioned error.
> 
> > Also how to you figure out that the issue was related to `socket.request.max.bytes` please?
> 
> The second line of the stacktrace references both `InvalidReceiveException` and the default value of `socket.request.max.bytes` (104857600 bytes). Have you tried using a larger value for that setting?

And I linked you to that issue because I thought the error was
`org.apache.kafka.common.errors.WakeupException: null` which was also referred to in that issue.

**Comment by francescopellegrini** [comment]
The `WakeupException` is a consequence of the issue, not the root cause. ;)

**Comment by francescopellegrini** [comment]
Hi @SarpongAbasimi, I'm sorry but, as I mentioned before, `WakeupException` is a consequence of the issue, not the root cause, so I'm not able to help you here.
